#!/usr/bin/env ruby
require 'webrick'
include WEBrick

dir = Dir::pwd
port = 8080

puts "URL: http://#{Socket.gethostname}:#{port} or http://localhost:#{port}"
 
s = HTTPServer.new(
    :Port            => port,
    :DocumentRoot    => dir
)
 
trap("INT"){ s.shutdown }
s.start