#!/bin/sh

#
#
#
#
#
#

if [ $# -ne 1 ]; then
	echo "usage: $0 [version]"
	exit 1
fi

VERSION=$1

pushd /tmp &> /dev/null

# Download the binaries
if [ ! -f ffmpeg-$VERSION.7z ]; then
	curl -O http://evermeet.cx/ffmpeg/ffmpeg-$VERSION.7z
fi 

if [ ! -f ffprobe-$VERSION.7z ]; then
	curl -O http://evermeet.cx/ffprobe/ffprobe-$VERSION.7z
fi

# extract 7zip files
7z e ffmpeg-$VERSION.7z
7z e ffprobe-$VERSION.7z

# move binaries into place
mv ffmpeg /usr/local/bin
mv ffprobe /usr/local/bin

# cleanup
rm *.7z

popd &> /dev/null