#!/bin/sh

echo "Updating rbenv"
pushd ~/.rbenv &> /dev/null
git pull

pushd plugins/ &> /dev/null

for dir in `ls`; do

	echo "Updating $dir"
	pushd $dir &> /dev/null
	git pull
	popd &> /dev/null

done
popd &> /dev/null
